name: Publish latest
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: export NODE_OPTIONS="--max_old_space_size=4096"

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'v'

      - run: |
          npm ci --force
          npm run build
          npm publish --access public
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}